### ISSUE TITLE
Write instructions on how to get started with the project for a newcomer.

### ISSUE THREAD

**Issue by smanilov** [DimoDimchev/Trivial#220] opened 2021-11-11 09:13 UTC
These should include
 - prerequisites
 - getting the code
 - getting the secrets
 - building and starting the project

When followed, they should always result in a working version of the project.

**Comment by DimoDimchev** [comment] 2021-12-14 09:54
duplicate of #319

**Closed by DimoDimchev** 2021-12-14 09:54 UTC
